Repository hashicorp/nomad-autoscaler, pull requests merged in 2020-08, with the labels that each got.

#237 deps: update CircleCI used Golang version to 1.14.7.
  .circleci/config.yml
  .circleci/config/config.yml
Labels: dependecy, enhancement

#239 deps: update Nomad dep to 0.12.2.
  go.mod
  go.sum
Labels: dependecy, enhancement

#238 agent: add initial telemetry implementation to emit key stats for monitoring
  agent/agent.go
  agent/config/config.go
  agent/config/config_test.go
  agent/health.go
  agent/health_test.go
  agent/http/error.go
  agent/http/error_test.go
  agent/http/health.go
  agent/http/health_test.go
  agent/http/metrics.go
  agent/http/metrics_test.go
  agent/http/server.go
  agent/http/server_test.go
  agent/telemetry.go
  command/agent.go
  go.mod
  go.sum
  plugins/manager/manager.go
  policy/file/source.go
  policy/manager.go
  policy/nomad/source.go
  policy/source.go
  policy/worker.go
Labels: agent, enhancement

#242 changelog: add entry for GH-238.
  CHANGELOG.md
Labels: documentation, enhancement

#243 metrics: use correct granularity identifier on metric key.
  plugins/manager/manager.go
  policy/worker.go
Labels: agent, bug

#241 Implements DatadogAPM plugin
  go.mod
  go.sum
  plugins/builtin/apm/datadog/main.go
  plugins/builtin/apm/datadog/plugin/plugin.go
  plugins/builtin/apm/datadog/plugin/plugin_test.go
Labels: apm, enhancement

#245 build: use Docker based CircleCI executor instead of VM.
  .circleci/config.yml
  .circleci/config/commands/install-go.yml
  .circleci/config/commands/install-golangci-lint.yml
  .circleci/config/config.yml
Labels: enhancement

#247 apm/datadog: add SetConfig function tests.
  plugins/builtin/apm/datadog/plugin/plugin_test.go
Labels: apm, enhancement

#244 docs: update documentation based on new Datadog APM.
  CHANGELOG.md
  README.md
Labels: documentation, enhancement

#250 command/agent: fix small help fomatting issue in agent CLI.
  command/agent.go
Labels: bug, cli

#249 apm/prometheus: add SetConfig function tests.
  plugins/builtin/apm/prometheus/plugin/plugin_test.go
Labels: apm, enhancement

#248 build: add go.sum to make target check alongside go.mod.
  GNUmakefile
Labels: enhancement
