Repository hashicorp/nomad-autoscaler, pull requests merged in 2020-10, with the labels that each got.

#277 target/nomad: support for namespaced jobs in scale and status RPC.
  plugins/builtin/target/nomad/plugin/plugin.go
  plugins/builtin/target/nomad/plugin/plugin_test.go
  plugins/builtin/target/nomad/plugin/state.go
  plugins/builtin/target/nomad/plugin/state_test.go
Labels: enhancement, target

#279 changelog: add entry for #277
  CHANGELOG.md
Labels: documentation, enhancement

#280 changelog: capitalise sentence start across all entries.
  CHANGELOG.md
Labels: documentation, enhancement

#288 version: allow setting custom metadata on version output.
  version/version.go
  version/version_test.go
Labels: enhancement

#293 demo: fix typo and ensure AWS AMI is private not public.
  demo/remote/aws.md
  demo/remote/packer/aws-packer.pkr.hcl
Labels: bug, demo

#294 demo/vagrant: add Nomad Autoscaler telemetry dashboard.
  demo/vagrant/README.md
  demo/vagrant/files/nomad_autoscaler_demo.json
  demo/vagrant/files/nomad_autoscaler_telemetry.json
  demo/vagrant/images/autoscaler_dashboard.png
  demo/vagrant/images/demo_dashboard.png
  demo/vagrant/jobs/autoscaler.nomad
  demo/vagrant/jobs/prometheus.nomad
Labels: demo, enhancement

#278 Add Azure VMSS target plugin
  GNUmakefile
  go.mod
  go.sum
  plugins/builtin/target/azure-vmss/main.go
  plugins/builtin/target/azure-vmss/plugin/azure.go
  plugins/builtin/target/azure-vmss/plugin/azure_test.go
  plugins/builtin/target/azure-vmss/plugin/plugin.go
  plugins/builtin/target/azure-vmss/plugin/plugin_test.go
  plugins/manager/internal.go
  plugins/plugin.go
  sdk/helper/ptr/ptr.go
  sdk/helper/scaleutils/filter.go
Labels: enhancement, plugins, target

#296 changelog: add entry for #278
  CHANGELOG.md
Labels: documentation, enhancement

#297 changelog: add entry for #282.
  CHANGELOG.md
Labels: documentation, enhancement

#299 changelog: add entry for Dynamic Application Sizing.
  CHANGELOG.md
Labels: documentation, enhancement

#300 deps: update Nomad API dependancy to latest master
  go.mod
  go.sum
Labels: dependecy, enhancement
