Repository hashicorp/nomad-autoscaler, pull requests merged in 2020-07, with the labels that each got.

#199 policy: namespace cluster target config params.
  plugins/builtin/target/aws-asg/plugin/aws.go
  plugins/builtin/target/aws-asg/plugin/aws_test.go
  plugins/builtin/target/aws-asg/plugin/plugin.go
  plugins/target/target.go
  policy/file/parse_test.go
  policy/file/test-fixtures/full-cluster-policy.hcl
  policy/policy_test.go
Labels: enhancement

#198 scaleutils: protect Autoscaler node from scale in.
  helper/scaleutils/nomad.go
Labels: enhancement

#201 changelog: add changelog entry for GH-197
  CHANGELOG.md
Labels: documentation

#202 changelog: add main AWS ASG cluster scaling changelog entries.
  CHANGELOG.md
Labels: enhancement

#200 policy: validate key params of policy struct.
  policy/file/parse_test.go
  policy/file/source.go
  policy/file/test-fixtures/full-task-group-policy.hcl
  policy/nomad/source.go
  policy/policy.go
  policy/policy_test.go
Labels: enhancement

#204 plugin/manager: ensure plugins are killed during manager tests.
  plugins/manager/manager_test.go
Labels: bug

#207 deps: update Nomad dep to 0.12.0-rc1 to accommodate API changes.
  go.mod
  go.sum
  policy/nomad/parser.go
  policy/nomad/validate.go
  policy/nomad/validate_test.go
Labels: dependecy, enhancement

#209 readme: update nightly build Nomad version requirement.
  README.md
Labels: documentation, enhancement

#210 deps: update Nomad dep to 0.12.0.
  CHANGELOG.md
  go.mod
  go.sum
Labels: dependecy, enhancement

#211 demo/vagrant: update Autoscaler version used to 0.1.0.
  demo/vagrant/jobs/autoscaler.nomad
Labels: demo, enhancement

#206 demo: add full horizontal scaling demo with AWS provider.
  .gitignore
  README.md
  demo/remote/README.md
  demo/remote/aws.md
  demo/remote/aws_autoscaler.nomad
  demo/remote/packer/aws-packer.pkr.hcl
  demo/remote/packer/config/10-consul.dnsmasq
  demo/remote/packer/config/99-default.dnsmasq.aws
  demo/remote/packer/config/consul.hcl
  demo/remote/packer/config/consul_aws.service
  demo/remote/packer/config/consul_client.hcl
  demo/remote/packer/config/nomad.hcl
  demo/remote/packer/config/nomad.service
  demo/remote/packer/config/nomad_client.hcl
  demo/remote/packer/scripts/client.sh
  demo/remote/packer/scripts/net.sh
  demo/remote/packer/scripts/server.sh
  demo/remote/packer/scripts/setup.sh
  demo/remote/terraform/env/aws/main.tf
  demo/remote/terraform/env/aws/outputs.tf
  demo/remote/terraform/env/aws/provider.tf
  demo/remote/terraform/env/aws/terraform.tfvars.sample
  demo/remote/terraform/env/aws/variables.tf
  demo/remote/terraform/modules/aws-hashistack/asg.tf
  demo/remote/terraform/modules/aws-hashistack/elb.tf
  demo/remote/terraform/modules/aws-hashistack/iam.tf
  demo/remote/terraform/modules/aws-hashistack/instances.tf
  demo/remote/terraform/modules/aws-hashistack/outputs.tf
  demo/remote/terraform/modules/aws-hashistack/sg.tf
  demo/remote/terraform/modules/aws-hashistack/templates.tf
  demo/remote/terraform/modules/aws-hashistack/templates/user-data-client.sh
  demo/remote/terraform/modules/aws-hashistack/templates/user-data-server.sh
  demo/remote/terraform/modules/aws-hashistack/variables.tf
  demo/remote/terraform/modules/aws-hashistack/version.tf
  demo/remote/terraform/modules/shared-nomad-jobs/files/grafana.nomad
  demo/remote/terraform/modules/shared-nomad-jobs/files/prometheus.nomad
  demo/remote/terraform/modules/shared-nomad-jobs/files/traefik.nomad
  demo/remote/terraform/modules/shared-nomad-jobs/files/webapp.nomad
  demo/remote/terraform/modules/shared-nomad-jobs/jobs.tf
  demo/remote/terraform/modules/shared-nomad-jobs/variables.tf
  demo/remote/terraform/modules/shared-nomad-jobs/version.tf
Labels: demo, enhancement

#203 docs: remove docs directory and point README to Nomad site.
  README.md
  docs/README.md
  docs/agent/README.md
  docs/api/README.md
  docs/cli/README.md
  docs/plugins/README.md
  docs/policy/README.md
Labels: documentation

#214 Fix Vagrant demo for Nomad 0.12
  demo/vagrant/files/nomad.hcl
Labels: bug, demo

#217 policy/file: add tests for getFilePolicyID func.
  policy/file/source_test.go
Labels: enhancement

#219 deps: update CircleCI used Golang version to 1.14.5.
  .circleci/config.yml
  .circleci/config/config.yml
Labels: dependecy, enhancement

#220 admin: add Jacquie as codeowner.
  .github/CODEOWNERS
Labels: admin, enhancement

#221 policy: fix issue when parsing non-default source name Nomad query.
  CHANGELOG.md
  agent/agent.go
  agent/plugins.go
  agent/plugins_test.go
  policy/file/source.go
  policy/nomad/source.go
  policy/nomad/testing.go
  policy/policy.go
  policy/policy_test.go
Labels: bug, policy

#223 plugins: fix issue launching multiple plugins using the same driver
  CHANGELOG.md
  plugins/manager/manager.go
  plugins/manager/util.go
  plugins/manager/util_test.go
Labels: bug, plugins

#224 deps: update CircleCI used Golang version to 1.14.6.
  .circleci/config.yml
  .circleci/config/config.yml
Labels: dependecy, enhancement

#230 demo/remote: fix aws-hashistack module provider region setup.
  demo/remote/terraform/env/aws/provider.tf
  demo/remote/terraform/modules/aws-hashistack/provider.tf
Labels: bug, demo

#231 demo/remote: add Nomad requirement to doc and remove Consul output
  demo/remote/README.md
  demo/remote/terraform/env/aws/outputs.tf
Labels: demo, enhancement

#233 demo: update remote version install of Nomad & Consul.
  demo/remote/packer/scripts/setup.sh
Labels: demo, enhancement

#235 demo/remote: remove use of custom node_class param.
  demo/remote/terraform/modules/aws-hashistack/templates.tf
  demo/remote/terraform/modules/aws-hashistack/variables.tf
Labels: bug, demo
