Repository hashicorp/nomad-autoscaler, pull requests merged in 2021-02, with the labels that each got.

#368 deps: update Prometheus client dependancy.
  go.mod
  go.sum
Labels: theme/dependency, type/enhancement

#369 changelog: add entry for #368
  CHANGELOG.md
Labels: theme/apm/prometheus, theme/dependency, type/enhancement

#353 Add GCE Managed Instance Group target plugin
  GNUmakefile
  go.mod
  go.sum
  plugins/builtin/target/gce-mig/main.go
  plugins/builtin/target/gce-mig/plugin/gce.go
  plugins/builtin/target/gce-mig/plugin/gce_test.go
  plugins/builtin/target/gce-mig/plugin/mig.go
  plugins/builtin/target/gce-mig/plugin/plugin.go
  plugins/builtin/target/gce-mig/plugin/plugin_test.go
  plugins/builtin/target/gce-mig/plugin/retry.go
  plugins/builtin/target/gce-mig/plugin/retry_test.go
  plugins/manager/internal.go
  plugins/plugin.go
  sdk/helper/scaleutils/filter.go
Labels: theme/cluster-scaling, type/enhancement

#373 update CHANGELOG
  CHANGELOG.md
Labels: theme/admin

#371 Add `node_drain_ignore_system_jobs` to `gce-mig` target
  plugins/builtin/target/gce-mig/plugin/gce.go
  plugins/builtin/target/gce-mig/plugin/gce_test.go
Labels: theme/demo/gcp, type/enhancement

#379 test: sync noop-test plugin go module files.
  plugins/test/noop-apm/go.sum
  plugins/test/noop-strategy/go.sum
  plugins/test/noop-target/go.sum
Labels: theme/testing, type/bug

#381 agent: fix Nomad config merging to pass env vars to plugins.
  agent/agent.go
  agent/agent_test.go
  agent/plugins.go
  agent/plugins_test.go
  sdk/helper/nomad/config.go
  sdk/helper/nomad/config_test.go
Labels: theme/agent, type/bug

#382 changelog: add entry for #381
  CHANGELOG.md
Labels: theme/docs, type/enhancement

#383 plugin/apm/prometheus: only access config map once to set config.
  plugins/builtin/apm/prometheus/plugin/plugin.go
Labels: stage/accepted, theme/apm/prometheus, type/enhancement

#347 ci: use single CircleCI config file.
  .circleci/.gitattributes
  .circleci/.gitignore
  .circleci/Makefile
  .circleci/README.md
  .circleci/config.yml
  .circleci/config/commands/install-go.yml
  .circleci/config/config.yml
  .circleci/config/jobs/build-go.yml
  .circleci/config/jobs/check-deps-go.yml
  .circleci/config/jobs/lint-go.yml
  .circleci/config/jobs/test-go.yml
  .circleci/config/workflows/ci.yml
Labels: stage/accepted, theme/ci, type/enhancement

#378 scaleutils: filter nodes to ensure unstable pools do not run eval.
  plugins/builtin/apm/nomad/plugin/node.go
  plugins/builtin/target/aws-asg/plugin/plugin.go
  plugins/builtin/target/azure-vmss/plugin/plugin.go
  plugins/builtin/target/gce-mig/plugin/plugin.go
  sdk/helper/scaleutils/filter.go
  sdk/helper/scaleutils/filter_test.go
  sdk/helper/scaleutils/status.go
Labels: theme/cluster-scaling, type/bug

#385 changelog: add entry for #378
  CHANGELOG.md
Labels: theme/docs, type/enhancement

#386 circleci: use Go 1.16 for CI testing.
  .circleci/config.yml
  go.sum
  tools/go.mod
  tools/go.sum
Labels: type/enhancement

#389 scaleutils: pass ignoreSystem drainspec param to drain monitor.
  sdk/helper/scaleutils/nomad.go
Labels: theme/cluster-scaling, type/bug

#392 plugin/target/aws-asg: check instances in non-running state.
  plugins/builtin/target/aws-asg/plugin/aws.go
Labels: stage/accepted, theme/target/aws-asg, type/bug

#393 changelog: add entry for #392
  CHANGELOG.md
Labels: theme/docs, type/enhancement

#394 demo/vagrant/horizontal: update job app versions deployed.
  demo/vagrant/horizontal-app-scaling/files/dashboard.json
  demo/vagrant/horizontal-app-scaling/jobs/grafana.nomad
  demo/vagrant/horizontal-app-scaling/jobs/haproxy.nomad
  demo/vagrant/horizontal-app-scaling/jobs/loki.nomad
  demo/vagrant/horizontal-app-scaling/jobs/prometheus.nomad
Labels: theme/demo/horizontal-app-scaling, type/enhancement

#396 demo/vagrant/das: update job app versions deployed.
  demo/vagrant/dynamic-app-sizing/jobs/das-autoscaler.nomad
  demo/vagrant/dynamic-app-sizing/jobs/das-load-test.nomad
  demo/vagrant/dynamic-app-sizing/jobs/example.nomad
  demo/vagrant/dynamic-app-sizing/jobs/prometheus.nomad
Labels: theme/demo/dynamic-app-sizing, type/enhancement

#352 Print metrics received from APM to debug log
  policyeval/base_worker.go
Labels: stage/accepted, stage/waiting-reply, theme/apm

#397 demo/azure: update and fix Azure demo
  demo/remote/azure/terraform/control/.terraform.lock.hcl
  demo/remote/azure/terraform/control/main.tf
  demo/remote/azure/terraform/modules/azure-hashistack/provider.tf
  demo/remote/azure/terraform/modules/azure-hashistack/templates/azure_autoscaler.nomad
Labels: theme/demo/azure, type/enhancement

#390 Expand SIGHUP handling
  agent/agent.go
  agent/config/config.go
  command/agent.go
  plugins/builtin/target/nomad/plugin/plugin.go
  plugins/manager/manager.go
  policy/manager.go
  policy/nomad/source.go
Labels: theme/agent, theme/plugins, theme/policy-source/nomad, type/enhancement

#367 demo/remote: add GCP Managed Instance group demo.
  demo/remote/README.md
  demo/remote/gcp/README.md
  demo/remote/gcp/packer/gcp-packer.pkr.hcl
  demo/remote/gcp/terraform/.gitignore
  demo/remote/gcp/terraform/control/.terraform.lock.hcl
  demo/remote/gcp/terraform/control/main.tf
  demo/remote/gcp/terraform/control/output.tf
  demo/remote/gcp/terraform/control/terraform.tfvars.sample
  demo/remote/gcp/terraform/control/variables.tf
  demo/remote/gcp/terraform/modules/gcp-hashistack/address.tf
  demo/remote/gcp/terraform/modules/gcp-hashistack/autoscaler.tf
  demo/remote/gcp/terraform/modules/gcp-hashistack/firewall.tf
  demo/remote/gcp/terraform/modules/gcp-hashistack/image.tf
  demo/remote/gcp/terraform/modules/gcp-hashistack/instance_group.tf
  demo/remote/gcp/terraform/modules/gcp-hashistack/lb.tf
  demo/remote/gcp/terraform/modules/gcp-hashistack/locals.tf
  demo/remote/gcp/terraform/modules/gcp-hashistack/network.tf
  demo/remote/gcp/terraform/modules/gcp-hashistack/output.tf
  demo/remote/gcp/terraform/modules/gcp-hashistack/project.tf
  demo/remote/gcp/terraform/modules/gcp-hashistack/provider.tf
  demo/remote/gcp/terraform/modules/gcp-hashistack/templates/gcp_autoscaler.nomad.tpl
  demo/remote/gcp/terraform/modules/gcp-hashistack/templates/user-data-client.sh
  demo/remote/gcp/terraform/modules/gcp-hashistack/templates/user-data-server.sh
  demo/remote/gcp/terraform/modules/gcp-hashistack/variables.tf
  demo/remote/gcp/terraform/modules/gcp-hashistack/vm.tf
  demo/remote/shared/packer/config/99-default.dnsmasq.gcp
  demo/remote/shared/packer/config/consul_gcp.service
Labels: theme/demo/gcp, type/enhancement

#395 scaleutils: refactor to make external plugins possible and easier
  plugins/builtin/apm/nomad/plugin/node.go
  plugins/builtin/apm/nomad/plugin/node_test.go
  plugins/builtin/target/aws-asg/plugin/aws.go
  plugins/builtin/target/aws-asg/plugin/aws_test.go
  plugins/builtin/target/aws-asg/plugin/plugin.go
  plugins/builtin/target/azure-vmss/plugin/azure.go
  plugins/builtin/target/azure-vmss/plugin/azure_test.go
  plugins/builtin/target/azure-vmss/plugin/plugin.go
  plugins/builtin/target/gce-mig/plugin/gce.go
  plugins/builtin/target/gce-mig/plugin/gce_test.go
  plugins/builtin/target/gce-mig/plugin/plugin.go
  sdk/helper/scaleutils/cluster.go
  sdk/helper/scaleutils/cluster_test.go
  sdk/helper/scaleutils/deprecated_filter.go
  sdk/helper/scaleutils/deprecated_filter_test.go
  sdk/helper/scaleutils/deprecated_nomad.go
  sdk/helper/scaleutils/deprecated_request.go
  sdk/helper/scaleutils/deprecated_request_test.go
  sdk/helper/scaleutils/deprecated_status.go
  sdk/helper/scaleutils/error.go
  sdk/helper/scaleutils/error_test.go
  sdk/helper/scaleutils/node_drain.go
  sdk/helper/scaleutils/node_drain_test.go
  sdk/helper/scaleutils/node_identifier.go
  sdk/helper/scaleutils/node_identifier_test.go
  sdk/helper/scaleutils/nodepool/class.go
  sdk/helper/scaleutils/nodepool/class_test.go
  sdk/helper/scaleutils/nodepool/nodepool.go
Labels: theme/cluster-scaling, type/enhancement

#400 changelog: add entry for #395
  CHANGELOG.md
Labels: stage/accepted, theme/docs, type/enhancement

#401 deps: update Nomad API dep to released 1.0.4.
  CHANGELOG.md
  go.mod
  go.sum
  plugins/test/noop-apm/go.sum
  plugins/test/noop-strategy/go.sum
  plugins/test/noop-target/go.sum
Labels: theme/dependency, type/enhancement
