Repository hashicorp/nomad-autoscaler, pull requests merged in 2021-04, with the labels that each got.

#439 changelog: add entries for #433 and #436
  CHANGELOG.md
Labels: theme/docs, type/enhancement

#440 makefile: add targets for fixed-value and pass-through plugins.
  GNUmakefile
Labels: theme/admin, type/enhancement

#441 policyeval: log error messages with error key.
  policyeval/base_worker.go
Labels: theme/policy-eval, type/bug

#450 Fix `empty` node selector strategy
  sdk/helper/scaleutils/nodeselector/empty.go
  sdk/helper/scaleutils/nodeselector/empty_test.go
  sdk/helper/scaleutils/nodeselector/least_busy_test.go
  sdk/helper/scaleutils/nodeselector/selector.go
  sdk/helper/scaleutils/nodeselector/test-fixtures/cluster1/151be1dc-92e7-a488-f7dc-49faaf5a4c96.json
  sdk/helper/scaleutils/nodeselector/test-fixtures/cluster1/README.md
  sdk/helper/scaleutils/nodeselector/test-fixtures/cluster1/b2d5bbb6-a61d-ee1f-a896-cbc6efe4f7fe.json
  sdk/helper/scaleutils/nodeselector/test-fixtures/cluster1/b535e699-1112-c379-c020-ebd80fdd9f09.json
  sdk/helper/scaleutils/nodeselector/testing.go
  sdk/target.go
Labels: theme/cluster-scaling

#452 ci: lint test file and fix problems
  .golangci.yml
  agent/agent_test.go
  plugins/manager/manager_test.go
  policy/file/parse_test.go
Labels: theme/ci, theme/testing, type/enhancement

#451 tools: update tool deps.
  tools/go.mod
  tools/go.sum
Labels: theme/dependency, theme/testing, type/enhancement

#457 circleci: use Go v1.16.3 to run tests.
  .circleci/config.yml
Labels: theme/dependency, theme/testing, type/enhancement

#458 add consul client to aget
  agent/agent.go
  agent/agent_test.go
  agent/config/config.go
  agent/config/config_test.go
  command/agent_test.go
  command/test-fixtures/agent_config_full.hcl
  go.mod
  go.sum
  plugins/test/noop-apm/go.sum
  plugins/test/noop-strategy/go.sum
  plugins/test/noop-target/go.sum
Labels: stage/accepted, theme/agent, type/enhancement

#463 chore: don't use fmt.Errorf when not formatting the error.
  agent/config/config.go
  plugins/builtin/apm/prometheus/plugin/plugin.go
  plugins/builtin/strategy/fixed-value/plugin/plugin_test.go
  plugins/builtin/strategy/target-value/plugin/plugin.go
  plugins/builtin/strategy/target-value/plugin/plugin_test.go
  plugins/builtin/target/gce-mig/plugin/gce.go
  plugins/builtin/target/nomad/plugin/state_test.go
  policy/handler.go
  policy/nomad/source.go
  policy/nomad/validate.go
  policy/nomad/validate_horizontal.go
  policy/nomad/validate_test.go
  policy/policy.go
  policyeval/broker.go
Labels: stage/accepted, type/enhancement

#462 sdk/helper: create error pkg to help with multierrors.
  sdk/helper/error/error.go
  sdk/helper/error/error_test.go
  sdk/helper/scaleutils/cluster.go
  sdk/helper/scaleutils/deprecated_filter.go
  sdk/helper/scaleutils/deprecated_filter_test.go
  sdk/helper/scaleutils/error.go
  sdk/helper/scaleutils/node_drain.go
  sdk/helper/scaleutils/node_drain_test.go
  sdk/helper/scaleutils/node_identifier.go
  sdk/helper/scaleutils/node_identifier_test.go
Labels: stage/accepted, type/enhancement

#464 admin: le sigh.
  .github/CODEOWNERS
Labels: stage/accepted, theme/admin, type/bug

#468 scaleutils: add datacenter nodepool implementation
  policy/policy.go
  policy/policy_test.go
  sdk/helper/scaleutils/cluster.go
  sdk/helper/scaleutils/cluster_test.go
  sdk/helper/scaleutils/node_identifier_test.go
  sdk/helper/scaleutils/nodepool/class.go
  sdk/helper/scaleutils/nodepool/datacenter.go
  sdk/helper/scaleutils/nodepool/datacenter_test.go
  sdk/helper/scaleutils/nodepool/nodepool.go
  sdk/helper/scaleutils/nodepool/nodepool_test.go
  sdk/policy.go
  sdk/policy_test.go
  sdk/target.go
Labels: stage/accepted, theme/cluster-scaling, type/enhancement

#469 changelog: add entry for #468
  CHANGELOG.md
Labels: stage/accepted, theme/docs, type/enhancement

#474 plugins/target/aws-asg: correctly order region config setting.
  plugins/builtin/target/aws-asg/plugin/aws.go
  plugins/builtin/target/aws-asg/plugin/aws_test.go
Labels: stage/accepted, theme/target/aws-asg, type/bug

#475 makefile: fix incorrect PHONY declarations.
  GNUmakefile
Labels: stage/accepted, theme/ci, type/bug

#476 changelog: add entry for #474
  CHANGELOG.md
Labels: stage/accepted, theme/docs, type/enhancement
