Repository hashicorp/nomad-autoscaler, pull requests merged in 2021-03, with the labels that each got.

#408 policy-manager: metric emit loop should use child context.
  policy/manager.go
Labels: stage/accepted, theme/policy, type/bug

#411 changelog: add entry for #408
  CHANGELOG.md
Labels: theme/docs, type/enhancement

#416 agent: return req error if prometheus metrics are disabled.
  CHANGELOG.md
  agent/http/agent_test.go
  agent/http/health_test.go
  agent/http/metrics.go
  agent/http/metrics_test.go
  agent/http/server.go
  agent/http/testing.go
  command/agent.go
Labels: theme/agent, theme/metrics, type/bug

#418 agent: fix issue causing incorrect debug/prom HTTP server config.
  command/agent.go
Labels: theme/agent, type/bug

#423 readme: update nightly build branch ref to main.
  README.md
Labels: stage/accepted, theme/docs

#422 Add configuration and CLI flags related to DAS
  agent/config/config.go
  agent/config/config_test.go
  agent/config/modes.go
  agent/config/modes_oss.go
  command/agent.go
  command/agent_test.go
  command/test-fixtures/agent_config_full.hcl
  command/test-fixtures/agent_config_small.hcl
  command/test-fixtures/agent_config_small_2.hcl
  sdk/helper/modes/flag.go
  sdk/helper/modes/flag_test.go
  sdk/helper/modes/modes.go
  sdk/helper/modes/modes_test.go
  sdk/helper/modes/set.go
  sdk/helper/modes/set_test.go
  sdk/helper/modes/struct.go
  sdk/helper/modes/struct_test.go
  sdk/helper/modes/testing.go
Labels: theme/cli, theme/dynamic-app-sizing, type/enhancement

#425 plugin/target/aws-asg: use single ASG call rather than split ASG/EC2 on scale-in.
  plugins/builtin/target/aws-asg/plugin/aws.go
  plugins/builtin/target/aws-asg/plugin/aws_test.go
  plugins/builtin/target/aws-asg/plugin/event.go
  plugins/builtin/target/aws-asg/plugin/plugin.go
  plugins/builtin/target/aws-asg/plugin/status.go
  plugins/builtin/target/aws-asg/plugin/status_test.go
  sdk/helper/scaleutils/cluster.go
  sdk/helper/scaleutils/node_drain.go
Labels: stage/accepted, theme/target/aws-asg, type/bug

#432 changelog: add entry for #425
  CHANGELOG.md
Labels: theme/docs, type/enhancement

#431 deps: ensure Nomad 1.0.4 API dep.
  go.mod
  go.sum
  plugins/test/noop-apm/go.mod
  plugins/test/noop-apm/go.sum
  plugins/test/noop-strategy/go.mod
  plugins/test/noop-strategy/go.sum
  plugins/test/noop-target/go.mod
  plugins/test/noop-target/go.sum
Labels: theme/dependency, type/enhancement

#434 deps: update dependancies for next minor release
  go.mod
  go.sum
  plugins/test/noop-apm/go.mod
  plugins/test/noop-apm/go.sum
  plugins/test/noop-strategy/go.mod
  plugins/test/noop-strategy/go.sum
  plugins/test/noop-target/go.mod
  plugins/test/noop-target/go.sum
Labels: theme/dependency, type/enhancement

#435 scaleutils: add nodeselector package to select nodes suitable for termination
  go.mod
  go.sum
  plugins/test/noop-apm/go.sum
  plugins/test/noop-strategy/go.sum
  plugins/test/noop-target/go.sum
  sdk/helper/scaleutils/cluster.go
  sdk/helper/scaleutils/nodeselector/empty.go
  sdk/helper/scaleutils/nodeselector/empty_test.go
  sdk/helper/scaleutils/nodeselector/least_busy.go
  sdk/helper/scaleutils/nodeselector/least_busy_test.go
  sdk/helper/scaleutils/nodeselector/newest_create_index.go
  sdk/helper/scaleutils/nodeselector/newest_create_index_test.go
  sdk/helper/scaleutils/nodeselector/selector.go
  sdk/helper/scaleutils/nodeselector/selector_test.go
  sdk/target.go
Labels: theme/cluster-scaling, type/enhancement

#437 changelog: add entries for #434 and #435
  CHANGELOG.md
Labels: theme/docs, type/enhancement
